### ISSUE TITLE
Why not "Auto-Property initializers" feature?

### ISSUE THREAD

**Issue by hoseinipeyrov** [mohammadfiroozi/Firoozi#3]
https://github.com/mohammadfiroozi/Firoozi/blob/3cf2a873ce9e0853419a44ad132e26d1e94c30a0/Firoozi.Domain/BasicInfo/Country.cs#L14-L20
you can use:
`public ICollection<Province> Provinces { get; set; } = new List<Province>();`
@mohammadfiroozi

**Comment by mohammadfiroozi** [comment]
that s a good idea 
thanks mr @hoseinipeyrov
